# Site settings
title: Sellnot.Me
email: sellnotme@gmail.com
url: http://sellnot.me
description: "SELLNOT.ME is Bangladesh's 1st Privacy Concerned Digital Shop, where you can buy anything and everything on request without sacrificing your private data."
keywords: "sell not me, sellnot.me, privacy shop, digital payment, dollar payment bd, youtube premium bd, super, best dollar shop bd, duolingo super price in bd, youtube premium price in bd, anonymous shop in bangladesh"
skills: "Sales Everything Except You and Your Private Data"
meta_author: SELLNOT.ME SalesEverythingExceptYou

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

 Contact form:
 - static : https://formspree.io/f/mnqkddgj
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: SELLNOT.ME
  location: location
  social: Around the Web
  credits: Slogan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/adnanraoha
  - title: facebook
    url: http://facebook.com/adnanraohalabib
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/ComingSoon
  - title: bitbucket
    url: http://bitbucket.org/comingSoon
  - title: github
    url: http://github.com/comingSoon

# Postal address (add as many lines as necessary)
address:
  - line: Mymensingh- 2200
  - line: Bangladesh

# Credits content
credits: 'Sellnot.me Sales Everything Except you. For your desired product/service/payment please kindly request here : sellnotme@gmail.com.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
